let salesData = [
  {
    idx: 0,
    className: "a",
    price: 10000,
    count: 1,
    userId: "a",
    lecturerId: "ad",
    dateOfPurchase: 43831,
  },
  {
    idx: 1,
    className: "b",
    price: 15000,
    count: 1,
    userId: "b",
    lecturerId: "a",
    dateOfPurchase: 43862,
  },
  {
    idx: 2,
    className: "c",
    price: 20000,
    count: 1,
    userId: "c",
    lecturerId: "b",
    dateOfPurchase: 43891,
  },
  {
    idx: 3,
    className: "d",
    price: 25000,
    count: 1,
    userId: "d",
    lecturerId: "c",
    dateOfPurchase: 43922,
  },
  {
    idx: 4,
    className: "e",
    price: 30000,
    count: 1,
    userId: "e",
    lecturerId: "d",
    dateOfPurchase: 43952,
  },
  {
    idx: 5,
    className: "f",
    price: 35000,
    count: 1,
    userId: "f",
    lecturerId: "e",
    dateOfPurchase: 43983,
  },
  {
    idx: 6,
    className: "g",
    price: 40000,
    count: 1,
    userId: "g",
    lecturerId: "f",
    dateOfPurchase: 44013,
  },
  {
    idx: 7,
    className: "h",
    price: 45000,
    count: 1,
    userId: "h",
    lecturerId: "g",
    dateOfPurchase: 44044,
  },
  {
    idx: 8,
    className: "i",
    price: 50000,
    count: 1,
    userId: "i",
    lecturerId: "h",
    dateOfPurchase: 44075,
  },
  {
    idx: 9,
    className: "j",
    price: 55000,
    count: 1,
    userId: "j",
    lecturerId: "i",
    dateOfPurchase: 44105,
  },
  {
    idx: 10,
    className: "k",
    price: 60000,
    count: 1,
    userId: "k",
    lecturerId: "j",
    dateOfPurchase: 44136,
  },
  {
    idx: 11,
    className: "l",
    price: 65000,
    count: 1,
    userId: "l",
    lecturerId: "k",
    dateOfPurchase: 44166,
  },
  {
    idx: 12,
    className: "m",
    price: 70000,
    count: 1,
    userId: "m",
    lecturerId: "l",
    dateOfPurchase: 44197,
  },
  {
    idx: 13,
    className: "n",
    price: 75000,
    count: 1,
    userId: "n",
    lecturerId: "m",
    dateOfPurchase: 44228,
  },
  {
    idx: 14,
    className: "o",
    price: 80000,
    count: 1,
    userId: "o",
    lecturerId: "n",
    dateOfPurchase: 44256,
  },
  {
    idx: 15,
    className: "p",
    price: 85000,
    count: 1,
    userId: "p",
    lecturerId: "o",
    dateOfPurchase: 44287,
  },
  {
    idx: 16,
    className: "q",
    price: 90000,
    count: 1,
    userId: "q",
    lecturerId: "p",
    dateOfPurchase: 44317,
  },
  {
    idx: 17,
    className: "r",
    price: 95000,
    count: 1,
    userId: "r",
    lecturerId: "q",
    dateOfPurchase: 44348,
  },
  {
    idx: 18,
    className: "s",
    price: 100000,
    count: 1,
    userId: "s",
    lecturerId: "r",
    dateOfPurchase: 44378,
  },
  {
    idx: 19,
    className: "t",
    price: 105000,
    count: 1,
    userId: "t",
    lecturerId: "s",
    dateOfPurchase: 44409,
  },
  {
    idx: 20,
    className: "u",
    price: 110000,
    count: 1,
    userId: "u",
    lecturerId: "t",
    dateOfPurchase: 44440,
  },
  {
    idx: 21,
    className: "v",
    price: 115000,
    count: 1,
    userId: "v",
    lecturerId: "u",
    dateOfPurchase: 44470,
  },
  {
    idx: 22,
    className: "w",
    price: 120000,
    count: 1,
    userId: "w",
    lecturerId: "v",
    dateOfPurchase: 44501,
  },
  {
    idx: 23,
    className: "x",
    price: 125000,
    count: 1,
    userId: "x",
    lecturerId: "w",
    dateOfPurchase: 44531,
  },
  {
    idx: 24,
    className: "y",
    price: 130000,
    count: 1,
    userId: "y",
    lecturerId: "x",
    dateOfPurchase: 44562,
  },
  {
    idx: 25,
    className: "z",
    price: 135000,
    count: 1,
    userId: "z",
    lecturerId: "y",
    dateOfPurchase: 44593,
  },
  {
    idx: 26,
    className: "a",
    price: 140000,
    count: 1,
    userId: "aa",
    lecturerId: "z",
    dateOfPurchase: 44621,
  },
  {
    idx: 27,
    className: "b",
    price: 145000,
    count: 1,
    userId: "ab",
    lecturerId: "aa",
    dateOfPurchase: 44652,
  },
  {
    idx: 28,
    className: "c",
    price: 150000,
    count: 1,
    userId: "ac",
    lecturerId: "ab",
    dateOfPurchase: 44682,
  },
  {
    idx: 29,
    className: "d",
    price: 155000,
    count: 1,
    userId: "ad",
    lecturerId: "ac",
    dateOfPurchase: 44713,
  },
  {
    idx: 30,
    className: "d",
    price: 155000,
    count: 1,
    userId: "ad",
    lecturerId: "ac",
    dateOfPurchase: 44713,
  },
  {
    idx: 31,
    className: "d",
    price: 155000,
    count: 1,
    userId: "ad",
    lecturerId: "ac",
    dateOfPurchase: 44713,
  },
  {
    idx: 32,
    className: "d",
    price: 155000,
    count: 1,
    userId: "ad",
    lecturerId: "ac",
    dateOfPurchase: 44713,
  },
  {
    idx: 33,
    className: "d",
    price: 155000,
    count: 1,
    userId: "ad",
    lecturerId: "ac",
    dateOfPurchase: 44713,
  },
  {
    idx: 34,
    className: "d",
    price: 155000,
    count: 1,
    userId: "ad",
    lecturerId: "ac",
    dateOfPurchase: 44713,
  },
  {
    idx: 35,
    className: "d",
    price: 155000,
    count: 1,
    userId: "ad",
    lecturerId: "ac",
    dateOfPurchase: 44713,
  },
  {
    idx: 36,
    className: "d",
    price: 155000,
    count: 1,
    userId: "ad",
    lecturerId: "ac",
    dateOfPurchase: 44713,
  },
  {
    idx: 37,
    className: "d",
    price: 155000,
    count: 1,
    userId: "ad",
    lecturerId: "ac",
    dateOfPurchase: 44713,
  },
  {
    idx: 38,
    className: "d",
    price: 155000,
    count: 1,
    userId: "ad",
    lecturerId: "ac",
    dateOfPurchase: 44713,
  },
  {
    idx: 39,
    className: "d",
    price: 155000,
    count: 1,
    userId: "ad",
    lecturerId: "ac",
    dateOfPurchase: 44713,
  },
  {
    idx: 40,
    className: "d",
    price: 155000,
    count: 1,
    userId: "ad",
    lecturerId: "ac",
    dateOfPurchase: 44713,
  },
  {
    idx: 41,
    className: "d",
    price: 155000,
    count: 1,
    userId: "ad",
    lecturerId: "ac",
    dateOfPurchase: 44713,
  },
];

export default salesData;
